### ISSUE TITLE
Bugs on login screen

### ISSUE THREAD

**Issue by doba16** [TaleTime/TaleTime_2#67]
### Describe the bug

Bugs and layout inconsistencies on this screen:

![image](https://github.com/TaleTime/TaleTime_2/assets/92383352/054df8f7-2337-44a5-b7ed-4af025347da8)

- [x] Duplicate word "Anmeldung" - Replace lower text with "Anmelden bei TaleTime" / "Log in to TaleTime"
- [x] More padding between Login button and registration link
- [x] The screen scrolls a bit although there is no need to scroll
- [x] The screen does not scroll enough if keyboard is open; keyboard hides login button
- [x] Navigation between input / login button fields not possible via keyboard
- [x] Keyboard should be e-mail keyboard
- [x] Placeholder texts barely fit the input

### Reproduction

Install app, open it and hit "Anmelden"

### System Info

```Shell
Android 9
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Login page:

I don't know if it would look better but could you vertically center the components other than the "Sie haben noch kein Konto?" Text?

**Comment by doba16** [comment]
They are centered!? Except for the "Forgot password" button. But it looks fine where it is.

**Comment by SamTV12345** [comment]
> They are centered!? Except for the "Forgot password" button. But it looks fine where it is.

I meant vertically centered. So that the widgets aren't put at the top.
