### ISSUE TITLE
Bugs on registration screen

### ISSUE THREAD

**Issue by doba16** [TaleTime/TaleTime_2#69]
### Describe the bug

Bugs and layout inconsistencies on this screen:

![image](https://github.com/TaleTime/TaleTime_2/assets/92383352/ba9501db-a408-4e75-b674-1e4aa628ae96)

- [x] Add a description what the username is used for
- [x] Navigation between input via keyboard not working
- [x] "Passwort bestätigen" is not required
- [x] "Passwort bestätigen" gets smaller when in error state and text is entered
![image](https://github.com/TaleTime/TaleTime_2/assets/92383352/b6bd6be5-4f0a-491f-a3d1-7cc7abc84f12)

### Reproduction

Install the app, open it and click on "Registrieren"

### System Info

```Shell
Android 9
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Reviewed.
