### ISSUE TITLE
Bugs on reset password screen

### ISSUE THREAD

**Issue by doba16** [TaleTime/TaleTime_2#70]
### Describe the bug

Bugs and layout inconsistencies on reset password screen:

![image](https://github.com/TaleTime/TaleTime_2/assets/92383352/29d1ca8d-a43e-4751-88a9-aae337dba8a8)

- [x] Too much padding above
- [x] Directly populate the e-mail input from the login screen

### Reproduction

Go to the password reset screen by clicking "Passwort vergessen?" on login screen

### System Info

```Shell
Android 9
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
There is a navigation bug. When I hit forget password and then click back on my phone I am redirected to the welcome screen.

**Comment by doba16** [comment]
This was intended as otherwise you would get across #73 again. I didn't think this would feel weird. However, I've changed it to work with back button to login screen.
