### ISSUE TITLE
Navigation between login and registration screens

### ISSUE THREAD

**Issue by doba16** [TaleTime/TaleTime_2#73]
### Describe the bug

When clicking between login and registration screens, all screens are stacked onto the navigation history. When Tapping the back button (in app bar as well as the android back button) you are sent to login screen many times.

### Reproduction

Click between login and registration many times and then go back by back button.

### System Info

```Shell
Android 9
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Reviewed.
