### ISSUE TITLE
Stories can be added to a profile multiple times

### ISSUE THREAD

**Issue by doba16** [TaleTime/TaleTime_2#90]
### Describe the bug

As the title indicates, a story can be added to a single profile multiple times.

### Reproduction

1. Add a story to your (listener) profile.
2. This story will appear on your listener home screen.
3. Go back to the all stories tab.
4. Add the same story again.
5. Go back to your listener home screen.
6. You can see the same story twice.

### System Info

```Shell
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (vor 5 Wochen) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
How do we want to solve this? Can we do that simply in dart by just filtering the already added stories?
